{
 "title": "ClientSideMetrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "API_min",
    "label": "Min_RT",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_all_min)"
    }
   },
   {
    "name": "API_max",
    "label": "Max_RT",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_all_max)"
    }
   },
   {
    "name": "API_avg",
    "label": "AVG_RT",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_all_mean)"
    }
   },
   {
    "name": "UserCount",
    "label": "ActiveUser",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_active)"
    }
   },
   {
    "name": "90th_RT",
    "label": "90th_RT",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_all_percentiles95)"
    }
   },
   {
    "name": "Errors",
    "label": "Errors",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_ko)"
    }
   },
   {
    "name": "Successful_Request",
    "label": "Successful",
    "query": {
     "query": "metrics(gatling_scalaclass_(.*)_ok_count)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Min Response Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "min($API_min)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg($API_avg{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max($API_max{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveUser",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "$UserCount{instance=\"graphite_exporter:9108\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalNumberOfUser",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_users_allUsers_done{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(gatling_scalaclass_allRequests_all_mean{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG RT VS 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "$API_avg{instance=\"graphite_exporter:9108\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "$90th_RT{instance=\"graphite_exporter:9108\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Vs 95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg($90th_RT{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "$UserCount{instance=\"graphite_exporter:9108\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(gatling_scalaclass_allRequests_all_percentiles95{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "75th Percentile Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(gatling_scalaclass_allRequests_all_percentiles75{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum($Successful_Request{instance=\"graphite_exporter:9108\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalNumberOfRequest Vs Failed Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "increase($Errors{instance=\"graphite_exporter:9108\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate($Successful_Request{instance=\"graphite_exporter:9108\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ActiveUsers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "$UserCount{instance=\"graphite_exporter:9108\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalFailedRequestCount",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "$Errors{instance=\"graphite_exporter:9108\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ConcurrentUsers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes($UserCount{instance=\"graphite_exporter:9108\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}